language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
notifications:
  email:
    sos-devel@redhat.com
  irc:
    channels:
      - "us.freenode.net#sosreport"
    on_success: change
install:
  - "pip install six nose nose-cov --use-mirrors"
  - "python setup.py install"
script:
  - "nosetests -v --with-cover --cover-package=sos --cover-html"
